// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/fingo-martpedia/fingo-transaction/external"
	"github.com/fingo-martpedia/fingo-transaction/helpers"
	"github.com/fingo-martpedia/fingo-transaction/internal/controller"
	"github.com/fingo-martpedia/fingo-transaction/internal/interfaces"
	"github.com/fingo-martpedia/fingo-transaction/internal/repository"
	"github.com/fingo-martpedia/fingo-transaction/internal/services"
	"gorm.io/gorm"
)

// Injectors from injector.go:

func InitDependency() Dependency {
	db := provideDB()
	transactionRepository := repository.NewTransactionRepository(db)
	walletExternal := external.NewWalletExternal()
	transactionService := services.NewTransactionService(transactionRepository, walletExternal)
	transactionController := controller.NewTransactionController(transactionService)
	dependency := Dependency{
		TransactionController: transactionController,
	}
	return dependency
}

// injector.go:

type Dependency struct {
	TransactionController interfaces.ITransactionController
}

func provideDB() *gorm.DB {
	return helpers.DB
}
